sudo: required
dist: trusty
language: coq
cache:
  apt: true
branches:
  only:
  - master
  - v1.0
env:
  global:
  - NJOBS=2
  # system is == 4.02.3
  - COMPILER="system"
  # Main test targets
  matrix:
  - COQ="8.6.1" MATHCOMP="1.6.1"
  - COQ="8.6.1" MATHCOMP="1.7.0"
  - COQ="8.7.2" MATHCOMP="1.7.0"
  - COQ="8.8.1" MATHCOMP="1.7.0"
  - COQ="8.8.1" MATHCOMP="dev"
  - COQ="dev" MATHCOMP="1.7.0"
  - COQ="dev" MATHCOMP="dev"
install:
- sudo add-apt-repository --yes ppa:avsm/ppa
- sudo apt-get update -qq
- sudo apt-get install -qq -y opam
- opam init -y
- eval $(opam config env)
- opam config var root
- opam remote add coq-extra-dev https://coq.inria.fr/opam/extra-dev
- opam remote add coq-core-dev  https://coq.inria.fr/opam/core-dev
- opam remote add coq-released  https://coq.inria.fr/opam/released
- opam pin add -nvy coq --kind version ${COQ}
- opam install -j ${NJOBS} -yv coq
- opam install -j ${NJOBS} -yv coq-mathcomp-ssreflect.${MATHCOMP}
- opam list
script:
- opam pin add -y -vvv .
